# Generated by Django 5.2.7 on 2025-10-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_school', models.CharField(blank=True, max_length=255, null=True)),
                ('diploma', models.CharField(blank=True, max_length=255, null=True)),
                ('diploma_school', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
